Algoritmo "SistemaCadastro"
Var
usuario, email, senha: caractere
Inicio
escreval("Seja bem-vindo ao sistema")
escreval("Para começar, vamos fazer seu cadastro, preencha os campos:")
escreval("Qual será o seu nome de usuário? ")
leia(usuario)
escreval("Qual é o seu email? ")
leia(email)
escreval("Qual será a sua senha? ")
leia(senha)
escreval("Seu cadastro foi finalizado ", usuario, "! Aproveite nossas utilidades.")
Fimalgoritmo