Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para x de 0 ate 50000 faca
escreval("O número atual é: ", x)
fimpara

Fimalgoritmo